import COLOR from '../Constants/color';
import {StyleSheet, Platform, Dimensions} from 'react-native';
import scale from '../utils/utils';
import color from '../Constants/color';
const {height} = Dimensions.get('window');
const DarkTheme = StyleSheet.create({
  buttonTab: {
    fontSize: 30,
    color: COLOR.black,
    fontWeight: '600',
    textAlign: 'center',
  },
  dashBoard: {
    flex: 1,
    paddingRight: '5%',
    backgroundColor: COLOR.black,

    paddingLeft: '5%',
  },
  livClass: {
    // flex: 1,
    paddingTop: 10,
    paddingRight: '3%',
    backgroundColor: COLOR.black,
    paddingLeft: '3%',
  },
  textWel: {
    fontSize: 18,
    color: COLOR.white,
  },
  candName: {
    fontSize: 18,
    marginTop: 3,
    color: COLOR.white,
    fontWeight: 'bold',
    letterSpacing: 2,
  },

  uppDash: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLOR.black,
  },
  appColor: {
    flex: 1,
    backgroundColor: COLOR.black,
  },
  crown: {
    color: COLOR.white,
    fontSize: 20,
  },
  registered: {marginLeft: 5, fontSize: 14, color: COLOR.white},
  userImage: {
    width: 80,
    height: 80,
    borderRadius: 50,
    backgroundColor: COLOR.grey,
  },
  courseCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: COLOR.darkPrimary,
    borderWidth: 1,
    // width: '28%',
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 10,
    height: 200,
    marginRight: 10,
    backgroundColor: '#369bcc',
  },
  registeredText: {
    color: COLOR.white,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 30,
    fontSize: 16,
  },
  courseBottomBtn: {marginBottom: 0, fontWeight: 'bold', color: COLOR.white},
  courseBottomText: {
    // marginTop: 20,
    // marginBottom: 20,
    color: COLOR.black,
    // height: 30,
    // width: '30%',
    textAlign: 'center',
  },
  courselockedBottomText: {
    opacity: 0.5,
    color: COLOR.black,
    textAlign: 'center',
  },
  documentBody: {
    paddingRight: '5%',
    backgroundColor: '#000',
    flex: 1,
    paddingLeft: '5%',
  },
  documentText: {
    fontSize: 24,
    color: COLOR.white,
    fontWeight: '600',
    textAlign: 'center',
  },
  documentStatus: {textAlign: 'center', fontSize: 18, color: COLOR.white},
  menuIcon: {fontSize: 40, color: COLOR.white, fontWeight: '800'},
  menuBtn: {
    ...Platform.select({
      ios: {
        width: 50,
        height: 45,
        borderRadius: 10,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLOR.lowPrimary,
      },
      android: {
        width: 50,
        height: 45,
        borderRadius: 10,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLOR.lowPrimary,
      },
    }),
  },
  selfLearn: {
    backgroundColor: '#000',
    flex: 1,
  },
  selfHeading: {fontSize: 18, color: COLOR.white},
  selfChapter: {fontSize: 26, fontWeight: 'bold', color: COLOR.white},
  quiz: {fontSize: 18, fontWeight: '300', marginBottom: 30, color: COLOR.white},
  assesment: {
    fontSize: 18,
    fontWeight: '300',
    marginBottom: 30,
    color: COLOR.white,
  },
  liveClassChapter: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#369DCC',
    borderRadius: 8,
    borderBottomRightRadius: 20,
    borderRightColor: COLOR.white,
    borderRightWidth: 9,
    borderBottomColor: COLOR.white,
    borderBottomWidth: 9,
    width: '48%',
    height: 200,
    position: 'relative',
  },
  chapterText: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
    color: COLOR.white,
  },
  chaptersList: {fontSize: 24, fontWeight: '600', color: COLOR.white},
  chapterHeader: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 20,
    color: COLOR.white,
  },
  chapterBox: {
    backgroundColor: '#369DCC',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 160,
    height: 160,
    borderRadius: 10,
  },
  lockedGlass: {
    fontSize: 90,
    color: COLOR.lowPrimary,
  },
  unlockGlass: {
    fontSize: 90,
    color: COLOR.white,
  },
  lockText: {textAlign: 'center', fontSize: 18, color: COLOR.white},
  chapterName: {fontSize: 16, color: COLOR.white, fontWeight: 'bold'},
  chapterTitle: {fontSize: 11, marginTop: 10, color: COLOR.white},
  chapterContainer: {
    width: 130,
    height: 130,
    borderRadius: 20,
    backgroundColor: COLOR.lowBlack,
    // padding: 10,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  chapterLockContainer: {
    width: 130,
    height: 130,
    borderRadius: 20,
    backgroundColor: 'transparent',
    // padding: 10,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  chapterUnlock: {
    // justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#369DCC',
    borderRightColor: '#FFF',
    borderRightWidth: 7,
    borderBlockColor: '#FFF',
    borderBottomWidth: 7,
    borderBottomRightRadius: 20,
    borderRadius: 8,
    width: '50%',
    height: 200,
  },
  documentPage: {
    width: '50%',
    height: 300,
    borderRadius: 20,
    backgroundColor: '#1F77BF',
  },
  documentModalText: {
    fontSize: 32,
    fontWeight: '600',
    color: COLOR.white,
    textAlign: 'center',
  },
  updateDate: {
    fontSize: 17,
    marginTop: 20,
    textAlign: 'center',
    color: COLOR.white,
  },
  cross: {color: COLOR.white, fontSize: 50},
  modalContainer: {
    flex: 1,
    paddingTop: 30,
    paddingLeft: '3%',
    paddingRight: '3%',
    backgroundColor: '#000',
  },
  orAnd: {marginTop: 30, marginBottom: 30, fontSize: 22, color: COLOR.white},
  //   modalDocument: {
  //     flex: 1,
  //     paddingTop: 30,
  //     backgroundColor: '#000',
  //   },
  modalDocument: {
    ...Platform.select({
      ios: {
        flex: 1,
        paddingTop: 30,
        backgroundColor: '#000',
      },
      android: {
        flex: 1,
        paddingTop: 10,
        backgroundColor: '#000',
      },
    }),
  },
  buttonTab: {
    fontSize: 30,
    color: COLOR.white,
    fontWeight: '600',
    textAlign: 'center',
  },
  modalContent: {
    padding: 20,
    backgroundColor: '#000',
    borderRadius: 10,
  },
  modalStatus: {textAlign: 'center', color: COLOR.white, fontSize: 18},
  documentCard: {
    width: 150,
    marginRight: 20,
    borderRadius: 20,
    backgroundColor: COLOR.darkPrimary,
    height: 250,
    padding: 20,
    // borderRightColor: isDone ? COLOR.darkPrimary : COLOR.white,
    // borderBottomColor: isDone ? COLOR.darkPrimary : COLOR.white,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  documentCard: {
    width: 150,
    marginRight: 20,
    borderRadius: 20,
    backgroundColor: '#2E90C8',
    height: 250,
    padding: 20,
    borderBlockColor: COLOR.grey,
    borderRightColor: COLOR.grey,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  documentLockCard: {
    width: 150,
    marginRight: 20,
    borderRadius: 20,
    backgroundColor: '#2E90C8',
    height: 250,
    padding: 20,
    borderBlockColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomWidth: 5,
    borderRightWidth: 5,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  documentCardText: {
    textAlign: 'center',
    fontWeight: '800',
    color: COLOR.white,
  },
  documentImage: {
    marginTop: 20,
    width: 90,
    height: 150,
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 10,
  },
  taskBox: {
    backgroundColor: COLOR.lowWhite,
    display: 'flex',
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderRadius: 10,
  },
  taskText: {
    fontSize: 16,
    width: '60%',
    color: COLOR.white,
    textAlign: 'center',
  },
  taskIcon: {fontSize: 40, color: COLOR.white},
  taskImage: {
    width: 60,
    height: 60,
    backgroundColor: 'rgba(256,256,256,0.1)',
    borderRadius: 10,
  },
  courseLockCard: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    height: '80%',
    width: 125,
    // width: '100%',
    borderRadius: 5,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  courseUnlockCard: {
    height: '80%',
    // width: '100%',
    width: 125,
    borderRadius: 5,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  dot: {
    width: 6,
    height: 6,
    backgroundColor: COLOR.grey,
    margin: 2,
  },
  darkDot: {
    width: 6,
    height: 6,
    backgroundColor: COLOR.white,
    margin: 2,
  },
  markComplete: {
    fontSize: 40,
    color: COLOR.white,
  },
  markNotComplete: {
    fontSize: 40,
    color: COLOR.grey,
  },
  levelName: {fontSize: 14, color: COLOR.white, fontWeight: '600'},
  plane: {fontSize: 40, color: COLOR.white, transform: [{rotate: '180deg'}]},
  planeDark: {
    transform: [{rotate: '0deg'}],
  },

  // Setting screen
  settingScreen: {
    flex: 1,
    padding: '3%',
    backgroundColor: COLOR.black,
  },
  settingIcon: {
    fontSize: 22,
    fontWeight: '600',
    color: COLOR.white,
  },
  commonBackground: {
    borderRadius: 10,
    backgroundColor: 'rgba(256,256,256,0.1)',
  },
  commonTouch: {
    marginLeft: 5,
    paddingLeft: 7,
    paddingRight: 15,
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginTop: 12,
    marginBottom: 12,
  },
  commonTouchInput: {
    marginLeft: 5,
    paddingLeft: 7,
    paddingRight: 15,
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginTop: 8,
    marginBottom: 8,
  },
  settingLeft: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  commonText: {
    fontSize: 16,
    marginLeft: 10,
    fontWeight: '500',
    color: COLOR.white,
  },
  upperText: {
    marginTop: 20,
    marginBottom: 5,
    fontSize: 17,
    fontWeight: '500',
    color: COLOR.white,
  },
  userinfo: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    marginLeft: 10,
    alignItems: 'flex-start',
  },
  email: {
    fontSize: 14,
    marginLeft: 10,
    color: COLOR.white,
  },
  logoutBox: {
    marginTop: 15,
  },
  logout: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(256,256,256,0.1)',
    width: '40%',
    borderRadius: 10,
    padding: 10,
    justifyContent: 'center',
  },
  logoutText: {
    fontSize: 18,
    marginLeft: 8,
    color: COLOR.white,
  },
  placeHolderText: {
    color: COLOR.white,
  },
  headerBackground: {
    backgroundColor: COLOR.black,
  },
  headerLeftIcon: {fontSize: 26, marginLeft: 10, color: COLOR.white},
  headerText: {
    color: COLOR.white,
  },
  bottomTab: {
    backgroundColor: COLOR.black,
    borderTopWidth: 0,
    borderTopColor: 'black',
  },
  liveClasscontainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  liveClasscard: {
    margin: scale(5),
    width: '99%',
    borderRadius: scale(15),
    backgroundColor: '#3B3B3B',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: scale(5),
    elevation: 3,
  },
  liveClasscardTitle: {
    fontSize: scale(15),
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#FFF',
  },
  medium: {
    textAlign: 'center',
    marginTop: scale(4),
    marginBottom: scale(8),
    fontSize: scale(12),
    color: color.white,
  },
  toggleButton: {
    paddingVertical: scale(10),
    paddingHorizontal: scale(20),
    borderRadius: scale(20),
    backgroundColor: '#3B3B3B',
    marginHorizontal: scale(5),
  },
  dayButton: {
    paddingVertical: scale(10),
    height: scale(40),
    paddingHorizontal: scale(15),
    borderRadius: scale(10),
    backgroundColor: '#3B3B3B',
    marginHorizontal: scale(5),
  },
  toggleText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  activeToggleText: {
    color: '#000',
  },
  dayText: {
    color: color.white,
  },
  regularContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  detailsContainer: {
    height: height * scale(0.63),
    padding: scale(10),
    backgroundColor: color.black,
    borderTopLeftRadius: scale(18),
    borderTopRightRadius: scale(18),
  },
  selfLearn: {
    paddingTop: 5,
    backgroundColor: 'black',
    flex: 1,
    paddingLeft: '3%',
    paddingRight: '3%',
  },
  levelcontainer: {
    flex: 1,
    padding: 10,
    backgroundColor: 'black',
  },
  chapterContainer: {
    flex: 1,
    backgroundColor: 'black',
    paddingHorizontal: 16,
  },
  quizScreen: {
    flex: 1,
    backgroundColor: '#000',
  },
  faqcontainer: {
    flex: 1,
    padding: scale(10),
    backgroundColor: color.black,
  },
  selfcardTitle: {
    fontSize: 18,
    fontWeight: '500',
    color: '#FFF',
    marginRight: 'auto',
  },
  cardDates: {
    marginTop: 4,
    fontSize: 16,
    color: '#FFF',
  },
  selfLearnChapter: {
    backgroundColor: color.black,
  },
  cardBox: {
    width: '100%',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#F5F5F5',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  flashCardcontainer: {
    flex: 1,
    backgroundColor: '#000',
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reading: {
    flex: 1,
    backgroundColor: '#000',
    padding: '3%',
  },
  marksContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
    paddingHorizontal: 20,
  },
  documentContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  packageContainer: {
    backgroundColor: '#000',
    padding: 20,
  },
  modalQuizText: {
    fontSize: scale(18),
    marginLeft: scale(7),
    color: color.white,
    fontWeight: 'bold',
  },
  upperModal: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: scale(12),
    backgroundColor: color.black,
  },
});
export default DarkTheme;
