import {StyleSheet} from 'react-native';
import COLOR from '../Constants/color';
import color from '../Constants/color';
import scale from '../utils/utils';

const LighTheme = StyleSheet.create({
  dashBoard: {
    paddingRight: '5%',
    backgroundColor: COLOR.white,
    paddingTop: 10,
    paddingLeft: '5%',
  },
  livClass: {
    // flex: 1,
    paddingTop: 10,
    paddingRight: '3%',
    backgroundColor: COLOR.white,
    paddingLeft: '3%',
  },
  uppDash: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLOR.white,
  },
  candName: {
    fontSize: 18,
    marginTop: 3,
    fontWeight: 'bold',
    color: COLOR.black,
    letterSpacing: 2,
  },
  textWel: {
    fontSize: 18,
    color: COLOR.black,
  },
  appColor: {
    flex: 1,
    backgroundColor: COLOR.white,
  },
  userImage: {
    width: 80,
    height: 80,
    borderRadius: 50,
    backgroundColor: 'blue',
  },
  courseCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: COLOR.lightSecondary,
    justifyContent: 'center',
    borderColor: COLOR.darkPrimary,
    borderWidth: 1,
    // width: '50%',
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 10,
    height: 200,
    marginRight: 10,
  },
  crown: {
    color: COLOR.black,
    fontSize: 20,
  },
  registered: {marginLeft: 5, fontSize: 14, color: COLOR.black},
  registeredText: {
    color: COLOR.darkPrimary,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 10,
    fontSize: 16,
  },
  courseLockCard: {
    backgroundColor: COLOR.unlockGrey,
    padding: 5,
    height: '80%',
    width: 125,
    // width: '100%',
    borderRadius: 5,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  courseUnlockCard: {
    position: 'relative',
    borderRadius: 5,
    backgroundColor: 'transparent',
    height: '80%',
    width: 125,
    // width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  courseBottomBtn: {
    marginBottom: 0,
    fontWeight: 'bold',
    color: COLOR.darkPrimary,
  },
  courseBottomText: {
    // marginTop: 20,
    // marginBottom: 20,
    color: COLOR.black,
    textAlign: 'center',
    // height: 30,
    // width: '30%',
  },
  courselockedBottomText: {
    // marginTop: 20,
    // marginBottom: 20,
    color: COLOR.black,
    opacity: 0.5,
    textAlign: 'center',
    // width: '60%',
  },
  documentBody: {
    paddingRight: '5%',
    backgroundColor: COLOR.white,
    flex: 1,
    paddingLeft: '5%',
  },
  documentText: {
    fontSize: 24,
    color: COLOR.black,
    fontWeight: '600',
    textAlign: 'center',
  },
  documentStatus: {textAlign: 'center', fontSize: 18, color: COLOR.black},
  menuIcon: {fontSize: 40, color: COLOR.white, fontWeight: '800'},
  menuBtn: {
    ...Platform.select({
      ios: {
        width: 50,
        height: 45,
        borderRadius: 10,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#777',
      },
      android: {
        width: 50,
        height: 45,
        borderRadius: 10,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#777',
      },
    }),
  },
  selfLearn: {
    backgroundColor: COLOR.white,
    flex: 1,
  },
  selfHeading: {fontSize: 18, color: COLOR.black},
  selfChapter: {fontSize: 26, fontWeight: 'bold', color: COLOR.black},
  quiz: {fontSize: 18, fontWeight: '300', marginBottom: 30, color: COLOR.black},
  assesment: {
    fontSize: 18,
    fontWeight: '300',
    marginBottom: 30,
    color: COLOR.black,
  },
  liveClassChapter: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLOR.lightSecondary,
    borderRadius: 8,
    borderBottomRightRadius: 20,
    borderRightColor: COLOR.darkPrimary,
    borderRightWidth: 7,
    borderBottomColor: COLOR.darkPrimary,
    borderBottomWidth: 7,
    width: '48%',
    height: 200,
    position: 'relative',
  },
  chaptersList: {fontSize: 24, fontWeight: '600', color: COLOR.black},
  chapterHeader: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 20,
    color: COLOR.black,
  },
  chapterBox: {
    backgroundColor: COLOR.lightSecondary,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 160,
    height: 160,
    borderRadius: 10,
  },
  lockedGlass: {
    fontSize: 90,
    color: COLOR.lowPrimary,
  },
  unlockGlass: {
    fontSize: 90,
    color: COLOR.darkPrimary,
  },
  lockText: {textAlign: 'center', fontSize: 18, color: COLOR.black},
  chapterName: {fontSize: 16, color: COLOR.darkPrimary, fontWeight: 'bold'},
  chapterTitle: {fontSize: 11, marginTop: 10, color: COLOR.white},
  chapterContainer: {
    width: 130,
    height: 130,
    borderRadius: 20,
    backgroundColor: COLOR.middleGrey,
    // padding: 10,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  chapterLockContainer: {
    width: 130,
    height: 130,
    borderRadius: 20,
    backgroundColor: 'transparent',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  chapterUnlock: {
    // justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLOR.lightPrimary,
    borderRightColor: COLOR.darkPrimary,
    borderRightWidth: 7,
    borderBlockColor: COLOR.darkPrimary,
    borderBottomWidth: 7,
    borderBottomRightRadius: 20,
    borderRadius: 8,
    width: '45%',
    height: 200,
  },
  documentPage: {
    width: '50%',
    height: 300,
    borderRadius: 20,
    backgroundColor: COLOR.lightSecondary,
  },
  documentModalText: {
    fontSize: 32,
    fontWeight: '600',
    color: COLOR.black,
    textAlign: 'center',
  },
  updateDate: {
    fontSize: 17,
    marginTop: 20,
    textAlign: 'center',
    color: COLOR.white,
  },
  cross: {color: COLOR.black, fontSize: 50},
  modalContainer: {
    flex: 1,
    paddingTop: 30,
    paddingLeft: '3%',
    paddingRight: '3%',
    backgroundColor: COLOR.white,
  },
  orAnd: {marginTop: 30, marginBottom: 30, fontSize: 22, color: COLOR.black},
  //   modalDocument: {
  //     flex: 1,
  //     paddingTop: 30,
  //     backgroundColor: COLOR.white,
  //   },
  modalDocument: {
    ...Platform.select({
      ios: {
        flex: 1,
        paddingTop: 30,
        paddingLeft: '2%',
        paddingRight: '2%',
        backgroundColor: COLOR.white,
      },
      android: {
        flex: 1,
        paddingLeft: '2%',
        paddingRight: '2%',
        paddingTop: 0,
        backgroundColor: COLOR.white,
      },
    }),
  },
  buttonTab: {
    fontSize: 30,
    color: COLOR.black,
    fontWeight: '600',
    textAlign: 'center',
  },
  modalContent: {
    backgroundColor: COLOR.white,
    borderRadius: 10,
  },

  modalStatus: {textAlign: 'center', color: COLOR.black, fontSize: 18},
  documentCard: {
    width: 150,
    marginRight: 20,
    borderRadius: 20,
    backgroundColor: COLOR.lightSecondary,
    height: 250,
    padding: 20,
    borderBlockColor: COLOR.darkPrimary,
    borderRightColor: COLOR.darkPrimary,
    // borderRightColor: isDone ? COLOR.darkPrimary : COLOR.white,
    // borderBottomColor: isDone ? COLOR.darkPrimary : COLOR.white,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  documentLockCard: {
    width: 150,
    marginRight: 20,
    borderRadius: 20,
    backgroundColor: COLOR.lightSecondary,
    height: 250,
    padding: 20,
    borderBlockColor: COLOR.white,
    borderRightColor: COLOR.white,
    // borderRightColor: isDone ? COLOR.darkPrimary : COLOR.white,
    // borderBottomColor: isDone ? COLOR.darkPrimary : COLOR.white,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  documentCardText: {
    textAlign: 'center',
    fontWeight: '800',
    color: COLOR.darkPrimary,
  },
  documentImage: {
    marginTop: 20,
    width: 90,
    height: 150,
    backgroundColor: COLOR.lighGrey,
    borderRadius: 10,
  },
  taskBox: {
    backgroundColor: COLOR.middleGrey,
    display: 'flex',
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderRadius: 10,
  },
  taskText: {fontSize: 16, width: '60%', textAlign: 'center'},
  taskIcon: {fontSize: 40, color: COLOR.black},
  taskImage: {
    width: 60,
    height: 60,
    backgroundColor: COLOR.darkGrey,
    borderRadius: 10,
  },
  dot: {
    width: 6,
    height: 6,
    backgroundColor: COLOR.grey,
    margin: 2,
  },
  darkDot: {
    width: 6,
    height: 6,
    backgroundColor: color.black,
    margin: 2,
  },
  markNotComplete: {
    fontSize: 40,
    color: COLOR.lowBlack,
  },
  markComplete: {
    fontSize: 40,
    color: color.darkPrimary,
  },
  levelName: {fontSize: 14, color: COLOR.black, fontWeight: '600'},
  plane: {
    width: scale(48),
    height: scale(48),
    zIndex: 999,
    color: COLOR.black,
    transform: [{rotate: '360deg'}],
  },

  // Setting page
  settingScreen: {
    flex: 1,
    padding: '3%',
    backgroundColor: '#EFEFEF',
  },
  settingIcon: {
    fontSize: 22,
    fontWeight: '600',
    color: COLOR.black,
  },
  commonBackground: {
    borderRadius: 10,
    backgroundColor: COLOR.white,
  },
  commonTouchInput: {
    marginLeft: 5,
    paddingLeft: 7,
    paddingRight: 15,
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginTop: 8,
    marginBottom: 8,
  },
  commonTouch: {
    marginLeft: 5,
    paddingLeft: 7,
    paddingRight: 15,
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginTop: 12,
    marginBottom: 12,
  },
  settingLeft: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  commonText: {
    fontSize: 16,
    marginLeft: 10,
    fontWeight: '500',
    color: COLOR.black,
  },
  upperText: {
    marginTop: 20,
    marginBottom: 5,
    fontSize: 17,
    fontWeight: '500',
    color: COLOR.black,
  },
  userinfo: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    marginLeft: 10,
    alignItems: 'flex-start',
  },
  email: {
    fontSize: 14,
    marginLeft: 10,
    color: COLOR.black,
  },
  logoutBox: {
    marginTop: 15,
  },
  logout: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLOR.white,
    width: '40%',
    borderRadius: 10,
    padding: 10,
    justifyContent: 'center',
  },
  logoutText: {
    fontSize: 18,
    marginLeft: 8,
    color: COLOR.black,
  },
  placeHolderText: {
    color: COLOR.black,
  },
  headerBackground: {
    backgroundColor: COLOR.white,
  },
  headerText: {
    color: COLOR.black,
  },
  headerLeftIcon: {fontSize: 26, marginLeft: 10, color: COLOR.black},
  bottomTab: {
    backgroundColor: COLOR.white,
    borderTopWidth: 0,
    borderTopColor: 'white',
  },
});

export default LighTheme;
