// Constants.js
export const ROUTES = {
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  RECOVERY_PASSWORD: 'Recovery password',
  RESET_PASSWORD: 'Reset password',
  OTP_SCREEN: 'Otp screen',
  LEVEL: 'LEVEL',
  READING: 'Reading',
  HOME: 'Home',
  HOME_TAB: 'Home Tab',
  MEETING: 'Meeting',
  HOME_DRAWER: 'Home Drawer',
  CHAPTERS: 'Chapters',
  SELF_LEARN_SCREEN: 'Self Learn Screen',
  PACKAGE: 'Package',

  LIVE_CLASS: 'Live Classes',
  SELF_LEARN: 'Self Learn',
  DOCUMENTS: 'Documents',
  FLASH: 'Flash',

  DASHBOARD: 'Dashboard',
  PROFILE_SETTING: 'Profile Setting',
  WELCOME: 'Welcome',
  FAQ: 'FAQ',
  REGULAR: 'Regular Pathway',
  PORTAL: 'Referral Portal',
  PRICING: 'Pricing',
  Installement: 'Instalment',
  QUIZ: 'Quiz',
  MARKS: 'Marks',
  LEADERBOARD: 'LeaderBoard',
};
